SELECT 'alteracoes' AS table_name, COUNT(*) AS rows_cnt FROM olddb.alteracoes UNION ALL 
SELECT 'autores' AS table_name, COUNT(*) AS rows_cnt FROM olddb.autores UNION ALL 
SELECT 'cidades' AS table_name, COUNT(*) AS rows_cnt FROM olddb.cidades UNION ALL 
SELECT 'colecoes_anexas' AS table_name, COUNT(*) AS rows_cnt FROM olddb.colecoes_anexas UNION ALL 
SELECT 'coletores' AS table_name, COUNT(*) AS rows_cnt FROM olddb.coletores UNION ALL 
SELECT 'coletores_complementares' AS table_name, COUNT(*) AS rows_cnt FROM olddb.coletores_complementares UNION ALL 
SELECT 'configuracao' AS table_name, COUNT(*) AS rows_cnt FROM olddb.configuracao UNION ALL 
SELECT 'enderecos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.enderecos UNION ALL 
SELECT 'especies' AS table_name, COUNT(*) AS rows_cnt FROM olddb.especies UNION ALL 
SELECT 'estados' AS table_name, COUNT(*) AS rows_cnt FROM olddb.estados UNION ALL 
SELECT 'familias' AS table_name, COUNT(*) AS rows_cnt FROM olddb.familias UNION ALL 
SELECT 'fase_sucessional' AS table_name, COUNT(*) AS rows_cnt FROM olddb.fase_sucessional UNION ALL 
SELECT 'generos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.generos UNION ALL 
SELECT 'herbarios' AS table_name, COUNT(*) AS rows_cnt FROM olddb.herbarios UNION ALL 
SELECT 'historico_acessos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.historico_acessos UNION ALL 
SELECT 'identificadores' AS table_name, COUNT(*) AS rows_cnt FROM olddb.identificadores UNION ALL 
SELECT 'locais_coleta' AS table_name, COUNT(*) AS rows_cnt FROM olddb.locais_coleta UNION ALL 
SELECT 'migrations' AS table_name, COUNT(*) AS rows_cnt FROM olddb.migrations UNION ALL 
SELECT 'paises' AS table_name, COUNT(*) AS rows_cnt FROM olddb.paises UNION ALL 
SELECT 'reflora' AS table_name, COUNT(*) AS rows_cnt FROM olddb.reflora UNION ALL 
SELECT 'reinos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.reinos UNION ALL 
SELECT 'relevos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.relevos UNION ALL 
SELECT 'remessas' AS table_name, COUNT(*) AS rows_cnt FROM olddb.remessas UNION ALL 
SELECT 'retirada_exsiccata_tombos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.retirada_exsiccata_tombos UNION ALL 
SELECT 'solos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.solos UNION ALL 
SELECT 'specieslink' AS table_name, COUNT(*) AS rows_cnt FROM olddb.specieslink UNION ALL 
SELECT 'sub_especies' AS table_name, COUNT(*) AS rows_cnt FROM olddb.sub_especies UNION ALL 
SELECT 'sub_familias' AS table_name, COUNT(*) AS rows_cnt FROM olddb.sub_familias UNION ALL 
SELECT 'telefones' AS table_name, COUNT(*) AS rows_cnt FROM olddb.telefones UNION ALL 
SELECT 'tipos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.tipos UNION ALL 
SELECT 'tipos_usuarios' AS table_name, COUNT(*) AS rows_cnt FROM olddb.tipos_usuarios UNION ALL 
SELECT 'tombos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.tombos UNION ALL 
SELECT 'tombos_fotos' AS table_name, COUNT(*) AS rows_cnt FROM olddb.tombos_fotos UNION ALL 
SELECT 'tombos_identificadores' AS table_name, COUNT(*) AS rows_cnt FROM olddb.tombos_identificadores UNION ALL 
SELECT 'tombo_alteracoes_antigas' AS table_name, COUNT(*) AS rows_cnt FROM olddb.tombo_alteracoes_antigas UNION ALL 
SELECT 'usuarios' AS table_name, COUNT(*) AS rows_cnt FROM olddb.usuarios UNION ALL 
SELECT 'variedades' AS table_name, COUNT(*) AS rows_cnt FROM olddb.variedades UNION ALL 
SELECT 'vegetacoes' AS table_name, COUNT(*) AS rows_cnt FROM olddb.vegetacoes 
