export default {
    400: 'Erro ao cadastrar o local de coleta.',
    401: 'Erro ao cadastrar a coleção anexa.',
    402: 'Erro ao buscar a familia.',
    403: 'Erro ao buscar a subfamilia.',
    404: 'Erro ao buscar a genero.',
    405: 'Erro ao buscar o especie.',
    406: 'Erro ao buscar a subespecie.',
    407: 'Erro ao buscar a variedade.',
    408: 'Erro ao cadastrar o tombo.',
    409: 'Erro ao cadastrar a identificacao.',
    410: 'Erro ao cadastrar os coletores no tombo.',
    411: 'Erro ao cadastrar a alteracao.',
    412: 'Esse tipo já está cadastrado.',
    413: 'Esse coletor já está cadastrado.',
    414: 'Erro ao cadastrar o coletor.',
    415: 'Erro ao buscar o coletor',
    416: 'Tombo não encontrado.',
};
