version: '3'

networks:
  default:
    driver: bridge

services:
  database:
    image: mysql:5.7
    container_name: herbario_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    build: ./herbario-backend
    container_name: herbario_app
    restart: always
    volumes:
      - $STORAGE_PATH:$STORAGE_PATH
    environment:
      NODE_ENV: $NODE_ENV
      DB_NAME: $DB_NAME
      DB_HOST: herbario_db
      DB_PORT: 3306
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      UPLOAD_PATH: $UPLOAD_PATH
      STORAGE_PATH: $STORAGE_PATH
    depends_on:
      - database

  web:
    build: ./herbario-frontend
    container_name: herbario_web
    restart: always
    environment:
      NODE_ENV: $NODE_ENV
      PUBLIC_URL: $PUBLIC_URL
      REACT_APP_API_URL: $API_BASE_URL
    depends_on:
      - app

  nginx:
    image: nginx:1.16-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - web

#  certbot:
#    build: ./certbot
#    container_name: certbot
#    restart: always
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt
#      - /var/www/html:/var/www/html
#    depends_on:
#      - nginx
