version: '3'

networks:
  default:
    driver: bridge

services:
  database:
    image: mysql:5.7
    container_name: herbario_db
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    build: ./herbario-backend
    container_name: herbario_app
    environment:
      NODE_ENV: $NODE_ENV
      DB_HOST: herbario_db
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      UPLOAD_PATH: $UPLOAD_PATH
      STORAGE_PATH: $STORAGE_PATH
    depends_on:
      - database

  painel:
    build: ./herbario-frontend
    container_name: herbario_painel
    environment:
      NODE_ENV: $NODE_ENV
      PUBLIC_URL: $PUBLIC_URL
      API_BASE_URL: $API_BASE_URL
    depends_on:
      - app

  nginx:
    image: nginx:1.16-alpine
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - painel
